package drools.spring.rules

import sbz.projekat.dto.RezultatSimptomiDTO;


global RezultatSimptomiDTO sviSimptomi;



rule "Groznica bolest"
    agenda-group "bolest"
    salience 100
    when
        $dto: String( this == "GROZNICA")
    then
        System.out.println("Groznica ");
        sviSimptomi.getOpsti().add("CURENJE IZ NOSA");
        sviSimptomi.getOpsti().add("BOL U GRLU");
        sviSimptomi.getOpsti().add("GLAVOBOLJA");
        sviSimptomi.getOpsti().add("KIJANJE");
        sviSimptomi.getOpsti().add("KASALJ");
        sviSimptomi.getOpsti().add("DRHTAVICA");
        sviSimptomi.getOpsti().add("TEMPERATURA VECA OD 38C");
end


rule "Prehlada bolest"
    agenda-group "bolest"
    salience 100
    when
        $dto: String( this == "PREHLADA")
    then
        System.out.println("Prehlada ");
        sviSimptomi.getOpsti().add("CURENJE IZ NOSA");
        sviSimptomi.getOpsti().add("BOL U GRLU");
        sviSimptomi.getOpsti().add("GLAVOBOLJA");
        sviSimptomi.getOpsti().add("KIJANJE");
        sviSimptomi.getOpsti().add("KASALJ");
end


rule "Upala krajnika bolest"
    agenda-group "bolest"
    salience 100
    when
        $dto: String( this == "UPALA KRAJNIKA")
    then
        System.out.println("Upala krajnika ");
        sviSimptomi.getOpsti().add("UMOR");
        sviSimptomi.getOpsti().add("BOL U GRLU");
        sviSimptomi.getOpsti().add("GLAVOBOLJA");
        sviSimptomi.getOpsti().add("BOL KOJI SE SIRI DO USIJU");
        sviSimptomi.getOpsti().add("GUBITAK APETITA");
        sviSimptomi.getOpsti().add("TEMPERATURA VECA OD 40C DO 41C");
        sviSimptomi.getOpsti().add("BOL KOJI SE SIRI DO USIJU");
         sviSimptomi.getOpsti().add("ZUTI SEKRET IZ NOSA");
         sviSimptomi.getOpsti().add("DRHTAVICA");
end



rule "Sinusna infekcija bolest"
    agenda-group "bolest"
    salience 100
    when
        $dto: String( this == "SINUSNA INFEKCIJA")
    then
        System.out.println("Dijabetes ");
        sviSimptomi.getOpsti().add("ZUTI SEKRET IZ NOSA");
        sviSimptomi.getOpsti().add("BOL U GRLU");
        sviSimptomi.getOpsti().add("GLAVOBOLJA");
        sviSimptomi.getOpsti().add("KASALJ");
        sviSimptomi.getOpsti().add("OTICANJE OKO OCIJU");
        sviSimptomi.getOpsti().add("TEMPERATURA VECA OD 38C");
        sviSimptomi.getSpecificni().add("BOLOVAO OD PREHLADE ILI GROZNICE U POSLEDNJIH 60 DANA");
end


rule "Dijabetes bolest"
    agenda-group "bolest"
    salience 100
    when
        $dto: String( this == "DIJABETES")
    then
        System.out.println("Dijabetes ");
        sviSimptomi.getOpsti().add("CESTO URINIRANJE");
        sviSimptomi.getOpsti().add("GUBITAK TELESNE TEZINE");
        sviSimptomi.getOpsti().add("MUCNINA I POVRACANJE");
        sviSimptomi.getOpsti().add("ZAMOR");
end



rule "Hipertenzija bolest"
    agenda-group "bolest"
    salience 100
    when
        $dto: String( this == "HIPERTENZIJA")
    then
        System.out.println("Hipertenzija ");
        sviSimptomi.getSpecificni().add("U POSLEDNJIH 6 MESECI ZABELEZENO BAREM 10 SLUCAJEVA VISOKOG PRITISKA");

end




rule "Hronicna bubrezna bolest bolest"
    agenda-group "bolest"
    salience 100
    when
        $dto: String( this == "HRONICNA BUBREZNA BOLEST")
    then
        System.out.println("Hronicna bubrezna bolest ");
        sviSimptomi.getOpsti().add("NOCTURIA");
        sviSimptomi.getOpsti().add("OTICANJE NOGU I ZGLOBOVA");
        sviSimptomi.getOpsti().add("GUSENJE");
        sviSimptomi.getOpsti().add("ZAMOR");
        sviSimptomi.getOpsti().add("BOL U GRUDIM");
        sviSimptomi.getSpecificni().add("BOLUJE OD HIPERTENZIJE VISE OD 6 MESECI");
        sviSimptomi.getSpecificni().add("BOLUJE OD DIJABETESA");
end


rule "Akutna bubrezna bolest bolest"
    agenda-group "bolest"
    salience 100
    when
        $dto: String( this == "AKUTNA BUBREZNA POVREDA")
    then
        System.out.println("Akutna bubrezna bolest ");
        sviSimptomi.getOpsti().add("OTICANJE NOGU I ZGLOBOVA");
        sviSimptomi.getOpsti().add("GUSENJE");
        sviSimptomi.getOpsti().add("ZAMOR");
        sviSimptomi.getOpsti().add("DIJAREJA");
        sviSimptomi.getSpecificni().add("OPORAVLJA SE OD OPERACIJE");
        sviSimptomi.getSpecificni().add("U POSLEDNJIH 14 DANA IMAO POVISENJU TELESNU TEMPERATURU");
        sviSimptomi.getSpecificni().add("U POSLEDNJIH 21 DANA PRIMAO ANTIBIOTIKE");
end
