package drools.spring.rules

import java.util.Date;
import sbz.projekat.model.Bolest;
import sbz.projekat.model.Lek;
import sbz.projekat.model.Simptom;
import sbz.projekat.dto.SveBolestiDTO;
import sbz.projekat.dto.DroolsDto;
import sbz.projekat.dto.CounterDTO;
import sbz.projekat.model.IstorijaBolesti;
import sbz.projekat.model.enums.TipLeka;


global SveBolestiDTO sveBolesti;


rule "Druga provera sve"
    agenda-group "sve"
    salience 999
    when
        $dto: DroolsDto()
    then
        System.out.println("Ima simptoma");
end


rule "Prva provera sve"
    agenda-group "sve"
    salience 1000
    when
        $temp: CounterDTO()
    then
        System.out.println("Evo counter");
end


rule "Prehlada sve"
    agenda-group "sve"
    salience 100
    when
        $temp: CounterDTO() @Watch(!vrednosti)
        $dto: DroolsDto($simptomi: simptomi)
        $komada : Number() from accumulate(
          String(
                this=="CURENJE IZ NOSA" || this=="BOL U GRLU" || this=="GLAVOBOLJA" || this=="KIJANJE" || this=="KASALJ"
            ) from $simptomi,
            init(int count = 0;),
            action(count += 1;),
            reverse(count -= 1;),
            result(count)
        )
    then
        System.out.println("Ima " + $komada + " simptoma za prehladu");
        $temp.getVrednosti().put("PREHLADA", $komada.intValue());
        update($temp)
        System.out.println($temp.getVrednosti().get("PREHLADA"));


end



rule "Groznica sve"
    agenda-group "sve"
    salience 100
    when
        $temp: CounterDTO() @Watch(!vrednosti)
        $dto: DroolsDto($simptomi: simptomi)
        $komada : Number() from accumulate(
          String(
                this=="CURENJE IZ NOSA" || this=="BOL U GRLU" || this=="GLAVOBOLJA" || this=="KIJANJE" || this=="KASALJ" || this=="DRHTAVICA" || this=="TEMPERATURA VECA OD 38C"
            ) from $simptomi,
            init(int count = 0;),
            action(count += 1;),
            reverse(count -= 1;),
            result(count)
        )
    then
        System.out.println("Ima " + $komada + " simptoma za groznicu");
        $temp.getVrednosti().put("GROZNICA", $komada.intValue());
        update($temp)

        System.out.println($temp.getVrednosti().get("GROZNICA"));

end


rule "Upala krajnika sve"
    agenda-group "sve"
    salience 100
    when
        $temp: CounterDTO() @Watch(!vrednosti)
        $dto: DroolsDto($simptomi: simptomi)
        $komada : Number() from accumulate(
          String(
                this=="UMOR" || this=="BOL U GRLU" || this=="GLAVOBOLJA" || this=="BOL KOJI SE SIRI DO USIJU" || this=="TEMPERATURA VECA OD 40C DO 41C" || this=="DRHTAVICA" || this=="GUBITAK APETITA" || this=="ZUTI SEKRET IZ NOSA"
            ) from $simptomi,
            init(int count = 0;),
            action(count += 1;),
            reverse(count -= 1;),
            result(count)
        )
    then
        System.out.println("Ima " + $komada + " simptoma za upalu krajnika");
        $temp.getVrednosti().put("KRAJNICI", $komada.intValue());
        update($temp)

        System.out.println($temp.getVrednosti().get("KRAJNICI"));

end



rule "Sinusna infekcija sve"
    agenda-group "sve"
    salience 100
    when
        $date : Date()
        $temp: CounterDTO() @Watch(!vrednosti)
        $dto: DroolsDto($simptomi: simptomi, $istorija : istorija)



        $komada : Number() from accumulate(
          String(
                this=="OTICANJE OKO OCIJU" || this=="BOL U GRLU" || this=="GLAVOBOLJA" || this=="TEMPERATURA VECA OD 38C" || this=="KASALJ"  || this=="ZUTI SEKRET IZ NOSA"
            ) from $simptomi,
            init(int count = 0;),
            action(count += 1;),
            reverse(count -= 1;),
            result(count)
        )

        $specijalan : Number() from accumulate(
                $is :  IstorijaBolesti(
                         $bolesti : bolesti,
                         $temp.checkDane($date, vreme, 60)
                    ) from $istorija,
                    init(int novi = 0;),
                    action(
                        for( Object b: $bolesti )
                            if("PREHLADA".equals(((Bolest)b).getNaziv()) || "GROZNICA".equals(((Bolest)b).getNaziv()) ) novi += 1;

                    ),
                    reverse(novi -= 1;),
                    result(novi)
                )


    then

            System.out.println("Ima obicni " + $komada + " simptoma za sinusnu infekciju");
            System.out.println("Ima specijalnih " + $specijalan + " simptoma za sinusnu infekciju");
            $temp.getVrednosti().put("SINUSI", $komada.intValue()+$specijalan.intValue());
            System.out.println($temp.getVrednosti().get("SINUSI"));
        update($temp)

end


rule "Ispis prvih provera sve"
    agenda-group "sve"
    salience 90
    when
        $temp: CounterDTO() @Watch(!vrednosti)
    then

        System.out.println("Ima simptoma za prehladu : " + $temp.getVrednosti().get("PREHLADA"));
        System.out.println("Ima simptoma za groznicu : " + $temp.getVrednosti().get("GROZNICA"));
        System.out.println("Ima simptoma za krajnike : " +  $temp.getVrednosti().get("KRAJNICI"));
        System.out.println("Ima simptoma za sinusnu infekciju : " + $temp.getVrednosti().get("SINUSI"));

end

rule "Dijabetes sve"
    agenda-group "sve"
    salience 80
    when
        $temp: CounterDTO() @Watch(!vrednosti)
        $dto: DroolsDto($simptomi: simptomi)
        $komada : Number() from accumulate(
          String(
               this=="CESTO URINIRANJE" || this=="GUBITAK TELESNE TEZINE" || this=="MUCNINA I POVRACANJE" || this=="ZAMOR"
            ) from $simptomi,
            init(int count = 0;),
            action(count += 1;),
            reverse(count -= 1;),
            result(count)
        )
    then
        System.out.println("Ima " + $komada + " simptoma za dijabetes");
        $temp.getVrednosti().put("DIJABETES", $komada.intValue());
        update($temp)

end


rule "Hipertenzija sve"
    agenda-group "sve"
    salience 100
    when
        $date : Date()
                $temp: CounterDTO() @Watch(!vrednosti)
                $dto: DroolsDto( $istorija : istorija)

                $specijalan : Number() from accumulate(
                                $is :  IstorijaBolesti(
                                         $simptom : simptomi,
                                         $temp.checkDane($date, vreme, 180)
                                    ) from $istorija,
                                    init(int novi = 0;),
                                    action(
                                        for( Object s: $simptom )
                                            if("VISOK PRITISAK".equals(((Simptom)s).getNaziv()) ) novi += 1;

                                    ),
                                    reverse(novi -= 1;),
                                    result(novi)
                                )


    then

        System.out.println("Ima specijalnih " + $specijalan + " simptoma za hipertenziju");
        $temp.getVrednosti().put("HIPERTENZIJA", $specijalan.intValue());
        update($temp)


end



rule "Ispis drugih provera sve"
    agenda-group "sve"
    salience 90
    when
        $temp: CounterDTO() @Watch(!vrednosti)
    then

        System.out.println("Ima simptoma za dijabetes : " + $temp.getVrednosti().get("DIJABETES"));
        System.out.println("Ima simptoma za hipertenziju : " + $temp.getVrednosti().get("HIPERTENZIJA"));

end




rule "Hronicna bubrezna bolest sve"
    agenda-group "sve"
    salience 60
    when
        $temp: CounterDTO() @Watch(!vrednosti)
        $date : Date()
        $dto: DroolsDto($simptomi: simptomi, $istorija : istorija)
        $komada : Number() from accumulate(
          String(
               this=="NOCTURIA" || this=="OTICANJE NOGU I ZGLOBOVA" || this=="GUSENJE" || this=="ZAMOR" || this=="BOL U GRUDIM"
            ) from $simptomi,
            init(int count = 0;),
            action(count += 1;),
            reverse(count -= 1;),
            result(count)
        )

        $specijalan1 : Number() from accumulate(
                                 $is :  IstorijaBolesti(
                                          $bolesti : bolesti
                                     ) from $istorija,
                                     init(int novi = 0;),
                                     action(
                                         for( Object b: $bolesti )
                                             if("DIJABETES".equals(((Bolest)b).getNaziv())) novi += 1;

                                     ),
                                     reverse(novi -= 1;),
                                     result(novi)
                                 )
         $specijalan2 : Number() from accumulate(
                                         $is :  IstorijaBolesti(
                                                 $temp.check6m($date, vreme),
                                                  $bolesti : bolesti
                                             ) from $istorija,
                                             init(int novi2 = 0;),
                                             action(
                                                 for( Object b: $bolesti )
                                                     if("HIPERTENZIJA".equals(((Bolest)b).getNaziv())) novi2 += 1;

                                             ),
                                             reverse(novi2 -= 1;),
                                             result(novi2 + $specijalan1.intValue())
                                         )

    then
        System.out.println("Ima opstih" + $komada + " simptoma za hronicu");
        System.out.println("Ima specijalnih" + $specijalan2.intValue() + " simptoma za hronicu");
        $temp.getVrednosti().put("HRONICNA", $komada.intValue()+$specijalan2.intValue());
        update($temp)

end



rule "Akutna bubrezna bolest sve"
    agenda-group "sve"
    salience 60
    when
        $temp: CounterDTO() @Watch(!vrednosti)
        $date : Date()
        $dto: DroolsDto($simptomi: simptomi, $istorija : istorija)
        $komada : Number() from accumulate(
          String(
              this=="OTICANJE NOGU I ZGLOBOVA" || this=="GUSENJE" || this=="ZAMOR" || this=="DIJAREJA"
            ) from $simptomi,
            init(int count = 0;),
            action(count += 1;),
            reverse(count -= 1;),
            result(count)
        )

        $specijalan1 : Number() from accumulate(
                                 $is :  IstorijaBolesti(
                                          $temp.checkDane($date, vreme, 14),
                                          $bolesti : bolesti
                                     ) from $istorija,
                                     init(int novi = 0;),
                                     action(
                                         for( Object b: $bolesti )
                                             if("GROZNICA".equals(((Bolest)b).getNaziv()) || "SINUSNA INFEKCIJA".equals(((Bolest)b).getNaziv()) || "UPALA KRAJNIKA".equals(((Bolest)b).getNaziv())) novi += 1;

                                     ),
                                     reverse(novi -= 1;),
                                     result(novi)
                                 )
        $specijalan2 : Number() from accumulate(
                                         $is :  IstorijaBolesti(
                                                 $temp.checkDane($date, vreme, 21),
                                                  $lek : terapija
                                             ) from $istorija,
                                             init(int novi2 = 0;),
                                             action(
                                                 for( Object l: $lek )
                                                     if( ((Lek)l).getTip() == TipLeka.ANTIBIOTIK ) novi2 += 1;

                                             ),
                                             reverse(novi2 -= 1;),
                                             result(novi2 + $specijalan1.intValue())
                                         )
        $specijalan3 : Number() from accumulate(
                                                 $is :  IstorijaBolesti(
                                                          $bol : bolesti
                                                     ) from $istorija,
                                                     init(int novi3 = 0;),
                                                     action(
                                                         for( Object b: $bol )
                                                              if("OPERACIJA".equals(((Bolest)b).getNaziv())) novi3 += 1;

                                                     ),
                                                     reverse(novi3 -= 1;),
                                                     result(novi3 + $specijalan2.intValue())
                                                 )

    then
        System.out.println("Ima opstih " + $komada + " simptoma za akutnu");
        System.out.println("Ima specijalnih " +$specijalan3.intValue() + " simptoma za akutnu");
        $temp.getVrednosti().put("AKUTNA", $komada.intValue()+$specijalan3.intValue());
        update($temp)

end

rule "Ispis trecih provera sve"
    agenda-group "sve"
    salience 50
    when
        $temp: CounterDTO() @Watch(!vrednosti)
    then

        System.out.println("Ima simptoma za hronicnu : " + $temp.getVrednosti().get("HRONICNA"));
        System.out.println("Ima simptoma za akutnu : " + $temp.getVrednosti().get("AKUTNA"));

end



rule "Odabir svega 3"
    agenda-group "sve"
    salience 40
    when
        $temp: CounterDTO() @Watch(!vrednosti)
    then

    int temp = $temp.getVrednosti().get("HRONICNA");
    if(temp>0)
        sveBolesti.getBolesti().add("HRONICNA BUBREZNA BOLEST");
    temp= $temp.getVrednosti().get("AKUTNA");
    if(temp>0)
        sveBolesti.getBolesti().add("AKUTNA BUBREZNA POVREDA");

end


rule "Odabir svega 2"
    agenda-group "sve"
    salience 40
    when
        $temp: CounterDTO() @Watch(!vrednosti)
    then

    int temp = $temp.getVrednosti().get("HIPERTENZIJA");
    if(temp>0)
        sveBolesti.getBolesti().add("HIPERTENZIJA");
    temp= $temp.getVrednosti().get("DIJABETES");
    if(temp>0)
        sveBolesti.getBolesti().add("DIJABETES");
end


rule "Odabir svega 1"
    agenda-group "sve"
    salience 40
    when
        $temp: CounterDTO() @Watch(!vrednosti)
    then

    int temp = $temp.getVrednosti().get("PREHLADA");
    if(temp>0)
        sveBolesti.getBolesti().add("PREHLADA");
    temp= $temp.getVrednosti().get("GROZNICA");
    if(temp>0)
        sveBolesti.getBolesti().add("GROZNICA");
    temp= $temp.getVrednosti().get("KRAJNICI");
    if(temp>0)
        sveBolesti.getBolesti().add("UPALA KRAJNIKA");
    temp= $temp.getVrednosti().get("SINUSI");
    if(temp>0)
        sveBolesti.getBolesti().add("SINUSNA INFEKCIJA");


end

